# Generated by Django 3.2.3 on 2021-10-03 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=56, verbose_name='Город')),
                ('city_name', models.CharField(max_length=56, verbose_name='название города')),
                ('temp', models.IntegerField(verbose_name='Температура')),
                ('pressure', models.IntegerField(verbose_name='Давление')),
                ('wind', models.IntegerField(verbose_name='Ветер')),
                ('icon', models.ImageField(upload_to='')),
            ],
            options={
                'verbose_name': 'Погода',
                'verbose_name_plural': 'Погода',
            },
        ),
    ]
