# Generated by Django 3.2.3 on 2021-10-04 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Weather',
        ),
    ]
